### ISSUE TITLE
[BUG] Flatpak version's menubar icon disappears after opening / closing the menu few times

### ISSUE THREAD

**Issue by sidevesh** [timschneeb/GalaxyBudsClient#504]
**Describe the bug**  
If the menu bar icon of the flatpak app is opened and closed a few times,
then the icon vanishes,
running the app from the flatpak runtime in console to see the error, I see following error when this happens:
```
** (process:38262): WARNING **: 17:23:02.912: Invalid client serial
```

**To Reproduce**  
Start the flatpak packaged app
Click on menu bar icon and close it
Repeat few times till it disappears

**Expected behavior**  
Menu bar icon should not disappears

**Desktop (please complete the following information):**  
 - Application version: 4.6.0 Flatpak, Arch Linux

Another error I saw when closing the app window that may be relevant:
```
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #13780214)
[17:23:01 INF] MainWindow.TitleBar: Close requested, minimizing to tray bar
```

**Comment by sidevesh** [comment]
yeah, the libadwaita version is too old on 22.04,
there won't be anything I can do in that case,
unless it's possible to upgrade libadwaita somehow

**Comment by sidevesh** [comment]
This issue is still present on the new version that was released on Flathub 3 days ago

**Comment by timschneeb** [comment]
This appears to be related to a bug in Avalonia: https://github.com/AvaloniaUI/Avalonia/issues/15551
