### ISSUE TITLE
[BUG] Process is running, but the program is not launching at all

### ISSUE THREAD

**Issue by kwon0408** [timschneeb/GalaxyBudsClient#520]
**Describe the bug**  
Process is running (shown in the Task Manager), but the program is not launching at all. No window, no tray icon.

**To Reproduce**  

1. Just run the program.

**Expected behavior**  
The main window and the tray icon should show up.

**Screenshots**  
N/A

**Desktop (please complete the following information):**  
 - OS: Windows 11 23H2 64bit, OS Build number 22631.3737, default system language: Korean
 - Application version: 5.0.0

**Additional context**  
* Similar to #489, but the tray icon is also missing this time.
* I have reinstalled several times, thinking whether there are any corrupted files. Below are their SHA256 hashes after the last attempt:
  * Installer: `2B197B08206DB196E07924D115914231073D42B380420AF5494E2754CDD8A919`
  * The main executable (same for both portable and setup version): `AB819C94709B89F5102703825EB48736DE52534898BE851A818C5264925ECDA8`

**Log files**  
[application.log](https://github.com/user-attachments/files/15981195/application.log)

**Comment by timschneeb** [comment]
This is related to issue #513. That bug prevents this app from launching correctly on some systems.

**Comment by kwon0408** [comment]
The problem is still not solved in v5.0.1.

**Comment by BoyceXX** [comment]
Double it, still crash here with v5.0.1. The same symptom.

**Comment by timschneeb** [comment]
In that case, I need to check again. I can't reproduce this issue which makes it a bit hard to debug

**Comment by BoyceXX** [comment]
> In that case, I need to check it again. I can't reproduce this issue, which makes it a bit hard to debug

I think it has somthing to do with bluetooth switch.
When it is on, Release 5.0.1 works fine. 
But when bluetooth was off before app startup, then it will crash.


Here is how the log file looks like on my pc after a crash of the app:

2024-07-02 09:16:57.197 +08:00 [INF] PlatformImpl: Using WindowsRtPlatformImplCreator
2024-07-02 09:16:57.219 +08:00 [DBG] Windows.HotkeyReceiver: WndProc probes attached
2024-07-02 09:16:57.294 +08:00 [DBG] WindowsRT.BluetoothService: Device watcher launched
2024-07-02 09:16:57.296 +08:00 [DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetoothc0:3c:59:db:06:d1-40:5e:f6:9d:fa:8d
2024-07-02 09:16:57.308 +08:00 [DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetooth0e:d1:45:dd:99:01-40:5e:f6:9d:fa:8d
2024-07-02 09:16:57.309 +08:00 [DBG] WindowsRT.BluetoothService: Device updated: Bluetooth#Bluetoothc0:3c:59:db:06:d1-40:5e:f6:9d:fa:8d
2024-07-02 09:16:57.312 +08:00 [ERR] Device info added
System.ArgumentException: 参数错误。

提供的设备 ID 不是有效的 BluetoothDevice 对象。
   at GalaxyBudsClient.Platform.WindowsRT.BluetoothService.<.ctor>b__35_4(DeviceWatcher watcher, DeviceInformation deviceInfo)
2024-07-02 09:16:57.315 +08:00 [INF] IpcService: Server listening at tcp:host=::1,port=54533
2024-07-02 09:16:57.323 +08:00 [DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetoothc0:3c:59:db:06:d1-54:10:4f:1e:1b:ac
2024-07-02 09:16:57.328 +08:00 [DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetoothc0:3c:59:db:06:d1-e8:7f:6b:9c:7f:7d
2024-07-02 09:16:57.846 +08:00 [DBG] WindowsRT.BluetoothService: Selected 'Boyce 的 Buds FE' (54:10:4f:1e:1b:ac) from cache as target
2024-07-02 09:16:58.082 +08:00 [INF] User script directory: C:\Users\xx\AppData\Local/GalaxyBudsClient/scripts
2024-07-02 09:16:58.082 +08:00 [INF] ScriptManager: 0 user script(s) found
2024-07-02 09:16:58.083 +08:00 [INF] Translator mode file location: C:\Users\xx\AppData\Local/GalaxyBudsClient/custom_language.xaml
2024-07-02 09:16:58.083 +08:00 [DBG] Environment: "Production"
2024-07-02 09:16:58.330 +08:00 [DBG] Windows.HotkeyReceiver: All hotkeys unregistered
2024-07-02 09:16:58.330 +08:00 [INF] Startup time: "00:00:01.3126364"
2024-07-02 09:16:58.743 +08:00 [DBG] WindowsRT.BluetoothService: Device updated: Bluetooth#Bluetoothc0:3c:59:db:06:d1-40:5e:f6:9d:fa:8d
2024-07-02 09:17:01.911 +08:00 [DBG] MainWindow.OnClosing: Termination cancelled
2024-07-02 09:17:13.684 +08:00 [ERR] WindowsRT.BluetoothService: Unknown error while connecting
System.Runtime.InteropServices.COMException (0x8007277C)
   at GalaxyBudsClient.Platform.WindowsRT.BluetoothService.ConnectAsync(String macAddress, String serviceUuid, CancellationToken cancelToken)
2024-07-02 09:17:16.434 +08:00 [DBG] WindowsRT.BluetoothService: Device enumeration complete
2024-07-02 09:17:16.435 +08:00 [DBG] WindowsRT.BluetoothService: Device updated: Bluetooth#Bluetoothc0:3c:59:db:06:d1-40:5e:f6:9d:fa:8d

**Comment by kwon0408** [comment]
Tried updating to v5.1.0, but the symptom is just the same as before.

And then I dived into the current code and found [a line in `GalaxyBudsClient.Platform.WindowsRT.BluetoothService`](https://github.com/timschneeb/GalaxyBudsClient/blob/master/GalaxyBudsClient.Platform.WindowsRT/BluetoothService.cs#L165) suspicious.

When a breakpoint is set on the line, it hits, but after the line is executed, my VS2022 gets out of the "paused" mode automatically.
