### ISSUE TITLE
[BUILD] Help needed to fix broken Nix package

### ISSUE THREAD

**Issue by Icy-Thought** [timschneeb/GalaxyBudsClient#538]
Greetings developers,

I at some point in time wrote a functional package that somehow turned into a non-functional one with the recent updates of this project. And since then I have been unable to fix the broken nix package and therefore I have decided to seek help here since I failed to attract dotnet developers from the nix community.

Due to my inexperience of dotnet, I am unable to resolve this issue without receiving some external help. (I have not found time to tinker with this and people are getting impatient)

The error I am encountering when attempting to run the built binary, which somehow reports no issues:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)
```

is as follows:

```
[10:52:51 INF] PlatformImpl: Using LinuxPlatformImplCreator
[10:52:51 INF] IpcService: Service listening on the session bus
[10:52:51 ERR] Unhandled exception in main thread
System.ArgumentException: An item with the same key has already been added. Key: /i18n/cn.axaml
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Avalonia.Platform.Internal.AssemblyDescriptor..ctor(Assembly assembly)
   at Avalonia.Platform.StandardAssetLoader..ctor(IAssemblyDescriptorResolver resolver, Assembly assembly)
   at Avalonia.Platform.StandardAssetLoader..ctor(Assembly assembly)
   at Avalonia.Platform.StandardRuntimePlatformServices.Register(Assembly assembly)
   at Avalonia.AppBuilder.<UseStandardRuntimePlatformSubsystem>b__68_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at GalaxyBudsClient.Program.Main(String[] args) in /build/source/GalaxyBudsClient/Program.cs:line 118
```

Package: [default.nix](https://github.com/Icy-Thought/nixpkgs/blob/GalaxyBudsClient/pkgs/applications/audio/galaxy-buds-client/default.nix)

Related:
- https://github.com/NixOS/nixpkgs/issues/306670
- https://github.com/NixOS/nixpkgs/issues/306671

**Comment by Icy-Thought** [comment]
If I remove `/i18n/cn.axaml` from the equation and proceed with the `postFixup` that I left in the file, I am greeted with a new error:

```
[11:07:37 INF] PlatformImpl: Using LinuxPlatformImplCreator
[11:07:37 INF] IpcService: Service listening on the session bus
[X11Platform] SMLib/ICELib reported a new error: SESSION_MANAGER environment variable not defined (X11PlatformLifetimeEvents #21224086)
[11:07:37 ERR] Unhandled exception in main thread
Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for GalaxyBudsClient.App, make sureto specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at GalaxyBudsClient.App.Initialize() in /build/source/GalaxyBudsClient/App.axaml.cs:line 70
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at GalaxyBudsClient.Program.Main(String[] args) in /build/source/GalaxyBudsClient/Program.cs:line 118
```

**Comment by Icy-Thought** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/353561.
