### ISSUE TITLE
[BUG]  Can't get JSON data from app

### ISSUE THREAD

**Issue by glsmith86** [timschneeb/GalaxyBudsClient#547]
OS: Ubuntu 24.04.1

glsmith@glsmith-Aspire-F5-771G:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=GalaxyBudsClient me.timschneeberger.GalaxyBudsClient device --get-all --json
[13:18:46 ERR] Unhandled exception in async task
Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name me.timschneeberger.GalaxyBudsClient was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at GalaxyBudsClient.Cli.CliHandler.ProcessDeviceVerb[T](ParserResult`1 result, DeviceOptions opts) in /run/build/GalaxyBudsClient/GalaxyBudsClient/Cli/CliHandler.cs:line 164
   at GalaxyBudsClient.Cli.CliHandler.ProcessDeviceVerb[T](ParserResult`1 result, DeviceOptions opts) in /run/build/GalaxyBudsClient/GalaxyBudsClient/Cli/CliHandler.cs:line 192
error: the Galaxy Buds Manager app is not active. The CLI can only be used while the app is running.

App run in background.

**Comment by glsmith86** [comment]
Portable version also not working:

glsmith@glsmith-Aspire-F5-771G:~$ GalaxyBudsClient_Linux_64bit_Portable.bin device --get-all
[10:10:56 ERR] Unhandled exception in async task
Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name me.timschneeberger.galaxybudsclient was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at GalaxyBudsClient.Cli.CliHandler.ProcessDeviceVerb[T](ParserResult`1 result, DeviceOptions opts)
   at GalaxyBudsClient.Cli.CliHandler.ProcessDeviceVerb[T](ParserResult`1 result, DeviceOptions opts)
error: the Galaxy Buds Manager app is not active. The CLI can only be used while the app is running.
glsmith@glsmith-Aspire-F5-771G:~$

**Comment by glsmith86** [comment]
Portable version also not working.

glsmith@glsmith-Aspire-F5-771G:~$ GalaxyBudsClient_Linux_64bit_Portable.bin device --get-all
[10:10:56 ERR] Unhandled exception in async task
Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name me.timschneeberger.galaxybudsclient was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at GalaxyBudsClient.Cli.CliHandler.ProcessDeviceVerb[T](ParserResult`1 result, DeviceOptions opts)
   at GalaxyBudsClient.Cli.CliHandler.ProcessDeviceVerb[T](ParserResult`1 result, DeviceOptions opts)
error: the Galaxy Buds Manager app is not active. The CLI can only be used while the app is running.
glsmith@glsmith-Aspire-F5-771G:~$
